Repository PvB-Groep-1/DevDorp, pull requests merged in 2020-04, with the labels that each got.

#2 <Feature: Events>
  Assets/Packages.meta
  Assets/Packages/CM.meta
  Assets/Packages/CM/Events.meta
  Assets/Packages/CM/Events/BoolEvent.cs
  Assets/Packages/CM/Events/BoolEvent.cs.meta
  Assets/Packages/CM/Events/CM.Events.asmdef
  Assets/Packages/CM/Events/CM.Events.asmdef.meta
  Assets/Packages/CM/Events/ColorEvent.cs
  Assets/Packages/CM/Events/ColorEvent.cs.meta
  Assets/Packages/CM/Events/FloatEvent.cs
  Assets/Packages/CM/Events/FloatEvent.cs.meta
  Assets/Packages/CM/Events/GameObjectEvent.cs
  Assets/Packages/CM/Events/GameObjectEvent.cs.meta
  Assets/Packages/CM/Events/IntEvent.cs
  Assets/Packages/CM/Events/IntEvent.cs.meta
  Assets/Packages/CM/Events/SimpleEvent.cs
  Assets/Packages/CM/Events/SimpleEvent.cs.meta
  Assets/Packages/CM/Events/StringEvent.cs
  Assets/Packages/CM/Events/StringEvent.cs.meta
  Assets/Packages/CM/Events/Vector2Event.cs
  Assets/Packages/CM/Events/Vector2Event.cs.meta
  Assets/Packages/CM/Events/Vector3Event.cs
  Assets/Packages/CM/Events/Vector3Event.cs.meta
Labels: feature

#3 <Feature: Window Api Backend>
  Assets/Scenes/MainMenuScene.unity
  Assets/Scenes/MainMenuScene.unity.meta
  Assets/Scenes/SampleScene.unity
  Assets/Scripts.meta
  Assets/Scripts/Backend.meta
  Assets/Scripts/Backend/Api.meta
  Assets/Scripts/Backend/Api/WindowApi.cs
  Assets/Scripts/Backend/Api/WindowApi.cs.meta
  Assets/Scripts/Backend/Hidden Classes.meta
  Assets/Scripts/Backend/Hidden Classes/Editor.meta
  Assets/Scripts/Backend/Hidden Classes/Editor/InitializeWindowsEditor.cs
  Assets/Scripts/Backend/Hidden Classes/Editor/InitializeWindowsEditor.cs.meta
  Assets/Scripts/Backend/Hidden Classes/InitializeStaticConstructors.cs
  Assets/Scripts/Backend/Hidden Classes/InitializeStaticConstructors.cs.meta
  Assets/Scripts/Backend/Hidden Classes/InitializeWindows.cs
  Assets/Scripts/Backend/Hidden Classes/InitializeWindows.cs.meta
  Assets/Scripts/Backend/Hidden Classes/OpenCloseWindow.cs
  Assets/Scripts/Backend/Hidden Classes/OpenCloseWindow.cs.meta
  Assets/Scripts/Enums.meta
  Assets/Scripts/Enums/WindowTypes.cs
  Assets/Scripts/Enums/WindowTypes.cs.meta
Labels: feature

#5 <Hotfix: Window Api Backend Commenting>
  Assets/Scripts/Backend/Api/WindowApi.cs
Labels: hotfix

#4 <Feature: Controls>
  ProjectSettings/InputManager.asset
Labels: feature

#7 <Feature: Boundaries>
  Assets/Scripts/Properties.meta
  Assets/Scripts/Properties/Boundary2D.cs
  Assets/Scripts/Properties/Boundary2D.cs.meta
Labels: feature

#6 <Feature: State Machine Backend>
  Assets/Scripts/Backend/State Machine.meta
  Assets/Scripts/Backend/State Machine/Abstract Class.meta
  Assets/Scripts/Backend/State Machine/Abstract Class/Action.cs
  Assets/Scripts/Backend/State Machine/Abstract Class/Action.cs.meta
  Assets/Scripts/Backend/State Machine/Abstract Class/Decision.cs
  Assets/Scripts/Backend/State Machine/Abstract Class/Decision.cs.meta
  Assets/Scripts/Backend/State Machine/Scriptable Objects.meta
  Assets/Scripts/Backend/State Machine/Scriptable Objects/State.cs
  Assets/Scripts/Backend/State Machine/Scriptable Objects/State.cs.meta
  Assets/Scripts/Backend/State Machine/StateController.cs
  Assets/Scripts/Backend/State Machine/StateController.cs.meta
  Assets/Scripts/Backend/State Machine/Transition.cs
  Assets/Scripts/Backend/State Machine/Transition.cs.meta
Labels: feature

#8 <Feature: World Api Backend>
  Assets/Scripts/Backend/Api/WorldApi.cs
  Assets/Scripts/Backend/Api/WorldApi.cs.meta
Labels: feature

#9 <Hotfix: World Api Backend To Static>
  Assets/Scripts/Backend/Api/WorldApi.cs
Labels: hotfix

#10 <Feature: Camera Zooming>
  Assets/Scenes/Development Scenes.meta
  Assets/Scenes/Development Scenes/CameraZoomingScene.unity
  Assets/Scenes/Development Scenes/CameraZoomingScene.unity.meta
  Assets/Scenes/GameScene.unity
  Assets/Scenes/GameScene.unity.meta
  Assets/Scripts/Features.meta
  Assets/Scripts/Features/Gameplay.meta
  Assets/Scripts/Features/Gameplay/Camera.meta
  Assets/Scripts/Features/Gameplay/Camera/CameraZooming.cs
  Assets/Scripts/Features/Gameplay/Camera/CameraZooming.cs.meta
  Assets/Scripts/Features/Gameplay/Camera/CameraZoomingEventSetter.cs
  Assets/Scripts/Features/Gameplay/Camera/CameraZoomingEventSetter.cs.meta
Labels: feature

#11 <Feature: Command>
  Assets/Packages/CM/Patterns.meta
  Assets/Packages/CM/Patterns/Command.meta
  Assets/Packages/CM/Patterns/Command/CM.Patterns.Command.asmdef
  Assets/Packages/CM/Patterns/Command/CM.Patterns.Command.asmdef.meta
  Assets/Packages/CM/Patterns/Command/Command.cs
  Assets/Packages/CM/Patterns/Command/Command.cs.meta
Labels: feature

#12 <Feature: Camera Dragging>
  Assets/Scenes/Development Scenes/CameraDraggingScene.unity
  Assets/Scenes/Development Scenes/CameraDraggingScene.unity.meta
  Assets/Scripts/Features/Gameplay/Camera/CameraDragging.cs
  Assets/Scripts/Features/Gameplay/Camera/CameraDragging.cs.meta
  Assets/Scripts/Features/Gameplay/Camera/CameraDraggingEventSetter.cs
  Assets/Scripts/Features/Gameplay/Camera/CameraDraggingEventSetter.cs.meta
  Assets/Scripts/Features/Gameplay/Camera/CameraZooming.cs
  Assets/Scripts/Features/Gameplay/Camera/CameraZoomingEventSetter.cs
Labels: feature

#13 <Hotfix: Unnecessary Run Class Constructor>
  Assets/Scripts/Backend/Hidden Classes/InitializeWindows.cs
Labels: hotfix

#18 <Feature: Building Placement>
  Assets/AI.meta
  Assets/AI/Actions.meta
  Assets/AI/Decisions.meta
  Assets/AI/States.meta
  Assets/AI/Villager.meta
  Assets/Scripts/Backend/DestroyObject.cs
  Assets/Scripts/Backend/DestroyObject.cs.meta
  Assets/Scripts/Backend/SpawnObject.cs
  Assets/Scripts/Backend/SpawnObject.cs.meta
Labels: feature

#21 <Feature: Buildings>
  Assets/Models.meta
  Assets/Models/Buildings.meta
  Assets/Models/Buildings/House 1.meta
  Assets/Models/Buildings/House 1/house_1.fbx
  Assets/Models/Buildings/House 1/house_1.fbx.meta
  Assets/Models/Buildings/House 1/house_1_mat.mat
  Assets/Models/Buildings/House 1/house_1_mat.mat.meta
  Assets/Models/Buildings/House 1/house_1_texture.png
  Assets/Models/Buildings/House 1/house_1_texture.png.meta
  Assets/Models/Buildings/Store.meta
  Assets/Models/Buildings/Store/store.fbx
  Assets/Models/Buildings/Store/store.fbx.meta
  Assets/Models/Buildings/Store/store_mat.mat
  Assets/Models/Buildings/Store/store_mat.mat.meta
  Assets/Models/Buildings/Store/store_texture.png
  Assets/Models/Buildings/Store/store_texture.png.meta
Labels: feature

#22 <Hotfix: Camera Method Order>
  Assets/Scripts/Features/Gameplay/Camera/CameraDragging.cs
Labels: hotfix

#24 <Hotfix: Remove Meta Files>
  Assets/AI.meta
  Assets/AI/Actions.meta
  Assets/AI/Decisions.meta
  Assets/AI/States.meta
  Assets/AI/Villager.meta
  Assets/Models/Flowers/flower03_green/flower03_green.fbx.meta
Labels: hotfix

#25 <Feature: Trees>
  Assets/Models/Trees.meta
  Assets/Models/Trees/Tree01.meta
  Assets/Models/Trees/Tree01/tree01.fbx
  Assets/Models/Trees/Tree01/tree01.fbx.meta
  Assets/Models/Trees/Tree01/tree01_texture.jpg
  Assets/Models/Trees/Tree01/tree01_texture.jpg.meta
  Assets/Models/Trees/Tree01/tree01_texture.mat
  Assets/Models/Trees/Tree01/tree01_texture.mat.meta
  Assets/Models/Trees/Tree02.meta
  Assets/Models/Trees/Tree02/tree02.fbx
  Assets/Models/Trees/Tree02/tree02.fbx.meta
  Assets/Models/Trees/Tree02/tree02_texture.jpg
  Assets/Models/Trees/Tree02/tree02_texture.jpg.meta
  Assets/Models/Trees/Tree02/tree02_texture.mat
  Assets/Models/Trees/Tree02/tree02_texture.mat.meta
  Assets/Models/Trees/Tree03.meta
  Assets/Models/Trees/Tree03/tree03.fbx
  Assets/Models/Trees/Tree03/tree03.fbx.meta
  Assets/Models/Trees/Tree03/tree03_texture.jpg
  Assets/Models/Trees/Tree03/tree03_texture.jpg.meta
  Assets/Models/Trees/Tree03/tree03_texture.mat
  Assets/Models/Trees/Tree03/tree03_texture.mat.meta
  Assets/Models/Trees/Tree04.meta
  Assets/Models/Trees/Tree04/tree04.fbx
  Assets/Models/Trees/Tree04/tree04.fbx.meta
  Assets/Models/Trees/Tree04/tree04_texture.jpg
  Assets/Models/Trees/Tree04/tree04_texture.jpg.meta
  Assets/Models/Trees/Tree04/tree04_texture.mat
  Assets/Models/Trees/Tree04/tree04_texture.mat.meta
Labels: feature

#26 <Feature: Rocks>
  Assets/Models/Rocks.meta
  Assets/Models/Rocks/rock_1.fbx
  Assets/Models/Rocks/rock_1.fbx.meta
  Assets/Models/Rocks/rock_2.fbx
  Assets/Models/Rocks/rock_2.fbx.meta
  Assets/Models/Rocks/rock_3.fbx
  Assets/Models/Rocks/rock_3.fbx.meta
  Assets/Models/Rocks/rock_4.fbx
  Assets/Models/Rocks/rock_4.fbx.meta
  Assets/Models/Rocks/rock_5.fbx
  Assets/Models/Rocks/rock_5.fbx.meta
  Assets/Models/Rocks/rocks_texture.png
  Assets/Models/Rocks/rocks_texture.png.meta
Labels: feature

#28 <Feature: Bakery>
  Assets/Models/Buildings/Bakery.meta
  Assets/Models/Buildings/Bakery/Bakery_basecolor.jpg
  Assets/Models/Buildings/Bakery/Bakery_basecolor.jpg.meta
  Assets/Models/Buildings/Bakery/Bakery_basecolor.mat
  Assets/Models/Buildings/Bakery/Bakery_basecolor.mat.meta
  Assets/Models/Buildings/Bakery/Bakery_food_basecolor.jpg
  Assets/Models/Buildings/Bakery/Bakery_food_basecolor.jpg.meta
  Assets/Models/Buildings/Bakery/Bakery_food_basecolor.mat
  Assets/Models/Buildings/Bakery/Bakery_food_basecolor.mat.meta
  Assets/Models/Buildings/Bakery/bakery.fbx
  Assets/Models/Buildings/Bakery/bakery.fbx.meta
  Assets/Models/Buildings/House 1/house_1_texture.tx
  Assets/Models/Buildings/House 1/house_1_texture.tx.meta
Labels: feature

#29 <Feature: Buildings>
  Assets/Models/Buildings/House 1/.mayaSwatches/house_1_texture.png_hcm.swatch
  Assets/Models/Buildings/House 1/house_1.fbx
  Assets/Models/Buildings/House 1/house_1.fbx.meta
  Assets/Models/Buildings/House 1/house_1_mat.mat
  Assets/Models/Buildings/House 1/house_1_mat.mat.meta
  Assets/Models/Buildings/House 1/house_1_texture.png.meta
  Assets/Models/Buildings/House 1/house_1_texture.tx
  Assets/Models/Buildings/House 1/house_1_texture.tx.meta
  Assets/Models/Buildings/Store/store 1.fbx
  Assets/Models/Buildings/Store/store 1.fbx.meta
  Assets/Models/Buildings/Store/store.fbx
  Assets/Models/Buildings/Store/store_mat.mat
  Assets/Models/Buildings/Store/store_mat.mat.meta
Labels: feature

#30 <Feature: Ground>
  Assets/Models/Ground.meta
  Assets/Models/Ground/ground.fbx
  Assets/Models/Ground/ground.fbx.meta
  Assets/Models/Ground/ground_basecolor.jpg
  Assets/Models/Ground/ground_basecolor.jpg.meta
  Assets/Models/Ground/ground_basecolor.mat
  Assets/Models/Ground/ground_basecolor.mat.meta
Labels: feature

#33 <Hotfix: Building Collision Check>
  Assets/Scripts/Backend/DestroyObject.cs
  Assets/Scripts/Backend/SpawnObject.cs
  ProjectSettings/TagManager.asset
Labels: hotfix

#36 <Hotfix: Camera Dragging Undefined>
  Assets/Prefabs.meta
  Assets/Prefabs/Main Camera.prefab
  Assets/Prefabs/Main Camera.prefab.meta
  Assets/Scenes/GameScene.unity
Labels: hotfix

#38 <Feature: Character>
  Assets/Models/Characters.meta
  Assets/Models/Characters/Character 1.meta
  Assets/Models/Characters/Character 1/character1.fbx
  Assets/Models/Characters/Character 1/character1.fbx.meta
  Assets/Models/Characters/Character 1/character1_idle.fbx
  Assets/Models/Characters/Character 1/character1_idle.fbx.meta
  Assets/Models/Characters/Character 1/character1_walk.fbx
  Assets/Models/Characters/Character 1/character1_walk.fbx.meta
  Assets/Models/Characters/Character 1/character_1_mat.mat
  Assets/Models/Characters/Character 1/character_1_mat.mat.meta
  Assets/Models/Characters/Character 1/character_1_texture.png
  Assets/Models/Characters/Character 1/character_1_texture.png.meta
Labels: feature

#40 <Feature: Readme Link to Docs>
  README.md
Labels: documentation, feature

#41 <Feature: Readme Documentation Link>
  README.md
Labels: documentation, feature

#43 <Feature: In Game UI>
  Assets/Images/In Game UI/coin.png
  Assets/Images/In Game UI/coin.png.meta
Labels: feature

#46 <Hotfix: Camera Dragging Threshold Low>
  Assets/Prefabs/Main Camera.prefab
Labels: hotfix

#47 <Feature: Readme Logo>
  Assets/Images/Dev Dorp.meta
  Assets/Images/Dev Dorp/devdorp_logo.png
  Assets/Images/Dev Dorp/devdorp_logo.png.meta
  README.md
Labels: documentation, feature
